### ISSUE TITLE
[YCQL] Add a flag to set consistency level for CQL workloads

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yb-sample-apps#33]
For Yugabyte we already have the `local_reads` flag to set the consistency level to `ONE` for reads, and that is sufficient (since our writes are always strongly-consistent).

However, the sample apps can be useful to run again other Cassandra implementations as a benchmark tool (e.g. vanilla Cassandra).
In that case, it would be useful to add more fine-grained flags for consistency level flags so that we could do apples-to-apples comparisons with other systems.
For instance, for a 3-node cluster we could set the write-consistency to QUORUM to be closer the Yugabyte's strongly-consistent writes.
Therefore, we could add two new flags: `cql_reads_consistency_level` and `cql_writes_consistency_level` that would respectively be used for reads and writes.
For instance, to run against vanilla Cassandra one could use:
```
java -jar target/yb-sample-apps.jar --workload CassandraKeyValue  \
                                    --nodes 127.0.0.1:9042,127.0.0.2:9042,127.0.0.3:9042  \
                                    --disable_yb_load_balancing_policy true \
                                    --cql_reads_consistency_level ONE \
                                    --cql_writes_consistency_level QUORUM
```
Note that `disable_yb_load_balancing_policy` is required for compatibility with non-Yugabyte servers.

**Comment by m-iancu** [comment]
After discussing with @kmuthukk, the easiest fix is to just switch the default write consistency to `QUORUM`. That already matches with Yugabyte default behavior for writes -- no need to add any new flags (and no changes needed for read path). cc @tedyu

**Comment by tedyu** [comment]
#34 has been merged.

Anything else to be done here ?

**Comment by m-iancu** [comment]
@tedyu Thanks, #34 indeed solves this, thanks! Closing the issue.
