### ISSUE TITLE
[Platform UI k8s] CPU metrics are not visible on overview page as well as Containers section on Metrics page on 2.4.4.0-b7 build universe.

### ISSUE THREAD

**Issue by nmantrav2** [yugabyte/yb-sample-apps#59]
1. Create a universe with 2.4.4.0-b7 build
2. Started YCQL and YSQL sample apps on it
3. Noticed that overview page and metrics page doesn't show use CPU metrics

**Comment by RP1807** [comment]
Observed this issue on the platform created using openshift helm-based installation. 
1. Create a universe with 2.6.0.0-b30 build 
2. Started YSQL sample apps 
3. Observed that CPU usage and Persistent Volume stats metrics are missing

**Comment by iSignal** [comment]
If we open these GH issues on this repo, I don't think they will be tracked in the main Platform queries. 

For helm based openshift, the issue may be expected. We may need to add docs to establish the workaround (unable to cc bhavin and Yatish)

**Comment by RP1807** [comment]
@iSignal yes, I have created https://github.com/yugabyte/yugabyte-db/issues/8976 here. We can close this issue from this repo. 
cc @VijiYB @nmantrav2
